### ISSUE TITLE
Request a token for Origin Trial

### ISSUE THREAD

**Issue by beaufortfrancois** [strangesast/bleno-web-pizza-example#2]
It would be nice if people didn't have to enable a flag to try out your demo.
Please request one OT token at http://bit.ly/WebBluetoothOriginTrial and include it in your html as described in https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web#available-for-origin-trials

@strangesast

**Comment by strangesast** [comment]
Got / added it! [1fd7adf](https://github.com/strangesast/bleno-web-pizza-example/commit/1fd7adf985e4ae242bee22cf1e842298bff2eaf5)
